### ISSUE TITLE
Custom helpers compiled incorrectly

### ISSUE THREAD

**Issue by luran813** [framework7io/framework7-loader#3]
1.template-helpers.js
```import { Template7 } from 'framework7/framework7.esm.bundle.js';

Template7.registerHelper('steps', function(step1, step2) {
  var str = 
    '<div class="steps">'+
      '<div class="step1">' + step1 + '</div>' +
      '<div class="step2">' + step2 + '</div>' +
    '</div>';
  return str;
});
module.exports = ['steps'];
```

2.  .f7.html content is:
`{{steps 'step1' 'step2'}}`

3. webpack.config.dev.js 
```{
        test: /\.f7.html$/,
        use: [
          'babel-loader',
          {
            loader: 'framework7-component-loader',
            options: {
              helpersPath: './src/js/template-helpers.js',
              partialsPath: './src/template/',
              partialsExt: '.f7p.html'
            }
          }
        ],
      },
```

4. Compile error :
```
ERROR in ./src/../aa.f7.html                                                                            
Module build failed (from ./node_modules/framework7-component-loader/lib/index.js):                                     
Error: Template7: Missing helper: "steps"                                                                               
    at Template7Class.compile (D:\luran\projects\xinge-pk-copy\bmanagersys\node_modules\template7\dist\template7.js:590:17)                                                                                                                     
    at Function.compile (D:\luran\projects\xinge-pk-copy\bmanagersys\node_modules\template7\dist\template7.js:655:21)   
    at Object.loader (D:\luran\projects\xinge-pk-copy\bmanagersys\node_modules\framework7-component-loader\lib\index.js:161:43)                                                                                                                 
```

**Comment by shastox** [comment]
Нужно добавить steps в этот файл: https://github.com/framework7io/framework7-template-webpack/blob/master/src/template7-helpers-list.js

**Comment by kriboogh** [comment]
I also get this error:
- defined the method name in template7-helpers-list.js: ['helper']
- registered the method in app.js before the app = new Framework7(...) call
- template is a f7.html file for a routable tab: {{helper param}}

Also get the missing helper error when opening the tab (framework 5.7.8)

**Comment by shastox** [comment]
Нужно перезапустить webpack

**Comment by kriboogh** [comment]
Already did that (several times), doesn't work.
